version: '3.6'

services:
  mainnet:
    image: realnuts/docker_dogecoind:1.14.2-0
    restart: always
    user: root
    command: dogecoind
    ports:
      - "8332:8332"
      - "8333:8333"
    volumes:
      - /opt/dogecoin/keys/mainnet:/dogecoin/wallet
      - /opt/dogecoin/blocks/mainnet:/dogecoin/.dogecoin/blocks
      - ./config/mainnet-dogecoin.conf:/dogecoin/.dogecoin/dogecoin.conf

  testnet:
    image: realnuts/docker_dogecoind:1.14.2-0
    restart: always
    user: root
    command: dogecoind
    ports:
      - "18332:18332"
      - "18333:18333"
    volumes:
      - /opt/dogecoin/keys/testnet:/dogecoin/wallet
      - /opt/dogecoin/blocks/testnet:/dogecoin/.dogecoin/testnet3/blocks
      - ./config/testnet-dogecoin.conf:/dogecoin/.dogecoin/dogecoin.conf
