version: '3.6'

services:
  mainnet:
    image: realnuts/docker_dogecoind:0.14.2-4
    restart: always
    user: root
    command: dogecoind
    ports:
      - "22555:22555"
      - "22556:22556"
    volumes:
      - /opt/blockchain_data/dogecoin:/home/dogecoin/.dogecoin/
      - ./config/mainnet.conf:/home/dogecoin/.dogecoin/dogecoin.conf
